"""Initial schema

Revision ID: cc6fcd9d459f
Revises: 
Create Date: 2026-08-30 16:46:53.224631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6fcd9d459f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_run_results',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('cases_processed', sa.Integer(), nullable=True),
    sa.Column('amount_at_risk', sa.Integer(), nullable=True),
    sa.Column('amount_recovered', sa.Integer(), nullable=True),
    sa.Column('recovery_rate', sa.Float(), nullable=True),
    sa.Column('false_escalation_rate', sa.Float(), nullable=True),
    sa.Column('exception_list', sa.JSON(), nullable=True),
    sa.Column('recovered_list', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_run_results_status'), 'batch_run_results', ['status'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('split', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_customer_id'), 'risk_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_risk_events_split'), 'risk_events', ['split'], unique=False)
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_case_id'), 'audit_log_entries', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_timestamp'), 'audit_log_entries', ['timestamp'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('root_cause_category', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_quadrant', sa.String(length=255), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('token_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_event_id'), 'diagnoses', ['event_id'], unique=False)
    op.create_table('guardrail_results',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_results_event_id'), 'guardrail_results', ['event_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('intervention_type', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_event_id'), 'interventions', ['event_id'], unique=False)
    op.create_table('promise_to_pays',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=True),
    sa.Column('promised_amount', sa.Integer(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('detected_via', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['risk_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promise_to_pays_case_id'), 'promise_to_pays', ['case_id'], unique=False)
    op.create_index(op.f('ix_promise_to_pays_status'), 'promise_to_pays', ['status'], unique=False)
    op.create_table('delivery_results',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('intervention_id', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('payment_link_id', sa.String(length=255), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_results_intervention_id'), 'delivery_results', ['intervention_id'], unique=False)
    op.create_index(op.f('ix_delivery_results_payment_link_id'), 'delivery_results', ['payment_link_id'], unique=False)
    op.create_index(op.f('ix_delivery_results_status'), 'delivery_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_results_status'), table_name='delivery_results')
    op.drop_index(op.f('ix_delivery_results_payment_link_id'), table_name='delivery_results')
    op.drop_index(op.f('ix_delivery_results_intervention_id'), table_name='delivery_results')
    op.drop_table('delivery_results')
    op.drop_index(op.f('ix_promise_to_pays_status'), table_name='promise_to_pays')
    op.drop_index(op.f('ix_promise_to_pays_case_id'), table_name='promise_to_pays')
    op.drop_table('promise_to_pays')
    op.drop_index(op.f('ix_interventions_event_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_guardrail_results_event_id'), table_name='guardrail_results')
    op.drop_table('guardrail_results')
    op.drop_index(op.f('ix_diagnoses_event_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_audit_log_entries_timestamp'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_case_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_index(op.f('ix_risk_events_split'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_customer_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_batch_run_results_status'), table_name='batch_run_results')
    op.drop_table('batch_run_results')
    # ### end Alembic commands ###
